# components/prd_generator.py
from langchain_core.language_models.chat_models import BaseChatModel
from app.core.project_generator.utils.prompt_loader import load_prompt
import datetime
from rich.panel import Panel
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from rich import print
callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])

def generate_prd(request: str, llm: BaseChatModel) -> str:
    """Generates the PRD markdown using the LLM."""
    prompt_template = load_prompt("prd_generator")

    # Inject context into the prompt
    current_date = datetime.datetime.now().strftime("%Y-%m-%d")
    system_context = (
        "This PRD is being generated as the first step in the LangChain Project Execution System. "
        "The goal is to align all stakeholders by clearly documenting the problem, goals, functional and non-functional requirements, "
        "technical architecture, and evaluation criteria for the upcoming LangChain-based application. "
        "This document serves as the foundational artifact for developers, product teams, and QA to execute the build plan efficiently."
    )
    target_audience = (
        "Developers, Team Leads, DevOps Engineers, QA Engineers, Product Managers. "
        "Each section of the PRD should be readable and actionable for its respective audience: "
        "- Developers need detailed specs and APIs; "
        "- QA Engineers require clear acceptance criteria; "
        "- DevOps needs infrastructure and deployment notes; "
        "- Product Managers need business alignment and measurable outcomes."
    )
    output_format_req = (
        "Strict Markdown format adhering to the structure specified below:\n\n"
        "# PRD: [Inferred Project Name]\n"
        "*Version: 1.0*\n"
        "*Date: [Current Date]*\n"
        "*Generated By: SpecCraft (LangChain Project Execution System)*\n\n"
        "## 1. Introduction\n"
        "   * **1.1. Purpose:** [Clearly articulate the primary goal and value proposition of the project...]\n"
        "   * **1.2. Scope:**\n"
        "      * **In Scope:** [List specific features...]\n"
        "      * **Out of Scope:** [List specific features not included...]\n"
        "   * **1.3. Definitions, Acronyms, and Abbreviations:** [Define terms used...]\n\n"
        "## 2. Goals and Objectives\n"
        "   * **2.1. Business Goals:** [High-level business rationale.]\n"
        "   * **2.2. Project Objectives:**\n"
        "      * Objective 1: [Description]\n"
        "      * Objective 2: [Description]\n"
        "   * **2.3. Success Metrics (Preliminary):** [Proposed ways to measure success.]\n\n"
        "## 3. User Stories\n"
        "   * **3.1. [User Role 1]:**\n"
        "      * US-001: As a [role], I want [action], so that [goal].\n"
        "   * **3.2. [User Role 2]:**\n"
        "      * US-002: ...\n\n"
        "## 4. Functional Requirements\n"
        "   * **FR-001:** The system *shall* [...]\n"
        "   * **FR-002:** ...\n\n"
        "## 5. Non-Functional Requirements (Inferred/Standard)\n"
        "   * **NFR-001 (Performance):** [...]\n"
        "   * **NFR-002 (Reliability):** [...]\n"
        "   * **NFR-003 (Usability):** [...]\n"
        "   * **NFR-004 (Security):** [...]\n"
        "   * **NFR-005 (Maintainability):** [...]\n"
        "   * **NFR-006 (Scalability):** [...]\n"
        "   * **NFR-007 (Portability):** [...]\n\n"
        "## 6. Assumptions\n"
        "   * **AS-001:** [...]\n"
        "   * **AS-002:** [...]\n\n"
        "## 7. Open Questions / Areas for Clarification\n"
        "   * **Q-001:** [...]\n"
        "   * **Q-002:** [...]\n"
        "   * **Q-003:** [...]\n"
    )

    # Replace placeholders in the master prompt template
    # Ensure your master prompt template uses placeholders like {PROJECT_REQUEST}, {SYSTEM_CONTEXT}, etc.
    formatted_prompt = prompt_template.format(
        PROJECT_REQUEST=request,
        CURRENT_DATE=current_date,
        SYSTEM_CONTEXT=system_context,
        TARGET_AUDIENCE=target_audience,
        OUTPUT_FORMAT_REQUIREMENT=output_format_req,
        # Add any other placeholders your specific PRD prompt needs
    )
    # Invoke the LLM
    # print(Panel(formatted_prompt, title="PRD Generator Prompt", border_style="green"))
    response = llm.invoke(formatted_prompt)

    # Assuming the response object has a 'content' attribute (common in LangChain)
    prd_markdown = response.content
    print(Panel(prd_markdown, title="PRD Markdown", border_style="green"))

    # Basic validation (optional, but recommended)
    if not prd_markdown:
         # Consider adding retry logic or more specific checks
         raise ValueError("LLM did not return a valid PRD markdown document.")
    return prd_markdown