from datetime import datetime
from langchain_core.language_models.chat_models import BaseChatModel
from app.core.project_generator.utils.prompt_loader import load_prompt
from rich.panel import Panel

"""
TASK GENERATION
takes in a prd_markdown, a request, a project_name, and a llm



"""


def generate_tasks(prd_markdown: str, project_name: str, llm: BaseChatModel) -> str:
    print("[cyan]Info: Loading Task Decomposer prompt template (Markdown version)...[/cyan]")
    prompt_template_decomp = load_prompt("task_decomposer") # Assumes this loads the MARKDOWN prompt
    primary_language_hint = "Python (Backend, using FastAPI) / TypeScript/JavaScript (Frontend, using Next.js/React) / HTML/CSS/JavaScript (Frontend, using React)"

            # Explains the purpose of this step and the requirements for the output,
            # emphasizing its use by downstream AI agents.
    system_context_decomp = """
            This task breakdown step immediately follows the PRD generation phase within the automated LangChain Project Execution System.
            The primary goal is to convert the preceding Product Requirements Document (PRD) into a actionable blueprint for building the software.
            The outputs generated by you (ArchitecTask) – specifically the 'Suggested File Structure' and the 'Task Checklist' in Markdown format – will be directly consumed by subsequent AI agents in the workflow:
            1.  **CodeCraft (Code Generator AI):** Will iterate through the Task Checklist, using each file's detailed task description to generate the corresponding source code.
            2.  **TestGenius (Test Creator AI):** Will analyze the generated source code and its original task description (from your checklist) to create automated tests.
            Therefore, the accuracy of the file paths, the extreme detail and clarity within each task description, the correct separation of backend (Python/FastAPI) and frontend (Next.js/TypeScript) concerns, and strict adherence to the requested Markdown output format are absolutely paramount for the overall success and automation capabilities of the system. Ambiguity or formatting errors will cause downstream failures.
            """

            # Precisely defines the expected output format, reinforcing the instructions
            # already present within the main body of the task_decomposer.prompt file.
    output_format_req_decomp = """
                        1. File Structure Section:
                        * Start exactly with the Markdown header: ## Suggested Project File Structure
                        * Follow immediately with a Markdown text code block (using triple backticks text ...).
                        * Inside the code block, present the hierarchical file structure tree using indentation or standard tree symbols (e.g., |--, | |--, etc.).
                        * The structure must accurately represent the directories and files derived only from the {PRD_DOCUMENT}. Based on the PRD analysis, this might include distinct top-level directories like backend/ and frontend/ for full-stack projects, only one of those for API-only or UI-only projects, or a flatter structure for CLI tools.
                        2. Task Checklist JSON Section:
                        * Start exactly with the Markdown header: ## Task Checklist JSON
                        * Follow immediately with a Markdown JSON code block (using triple backticks with json language identifier: json ...).
                        * Inside the code block, provide a single, valid JSON object. This object must contain a single top-level key "task_checklist", which holds an array [] of task objects.
                        * Task Object Structure: Each object within the "task_checklist" array represents the task for one file from the Suggested Project File Structure and MUST contain the following keys:
                        * "file_path": (String) The exact relative path to the file from the project root (e.g., "/backend/src/main.py", "/greeter.py"). Must match the file structure precisely.
                        * "task": (Object) Contains the core details of the implementation task.
                        * "description": (String) A detailed, clear natural language description of this file's specific purpose and the primary actions to be implemented within it, derived directly from the PRD. Explain what the file does and why it exists in the context of the PRD's goals.
                        * "requirements": (Array of Strings) A list of all PRD requirement IDs (e.g., "FR-001", "NFR-005") that this file's implementation directly addresses or contributes to fulfilling. Find all relevant IDs by cross-referencing the file's purpose with the PRD sections.
                        * "technical_spec": (Object) Detailed technical specifications for implementation. Populate only relevant sub-keys based on file type and PRD needs. Include sub-keys like:
                        * "imports": (Array of Strings) List necessary standard library, third-party (from PRD/dependencies), and relative project imports.
                        * "exports": (Array of Strings) List key functions, classes, variables, components exported.
                        * "functions": (Array of Objects) Describe functions with "name", "params", "returns", "purpose".
                        * "classes": (Array of Objects) Describe classes with "name", "inherits_from", "properties" (array of objects with "name", "type", "purpose"), "methods" (array like functions), "purpose".
                        * "interfaces": (Array of Objects) Describe TS interfaces with "name", "properties" (array of objects with "name", "type", "is_optional"), "purpose".
                        * "component_props": (Array of Objects) Describe React component props with "name", "type", "is_optional", "purpose".
                        * "api_endpoints": (Array of Objects) Describe FastAPI endpoints with "method", "path", "request_model", "response_model", "status_code", "purpose".
                        * "error_handling": (String, Optional) Specific error handling instructions from PRD.
                        * "notes": (String, Optional) Other critical implementation details, constraints, or conventions from PRD (e.g., "Must use argparse per FR-002", "Adhere strictly to PEP 8 per NFR-005").
                        * "metadata": (Object) Additional information about the task.
                        * "estimated_hours": (Number) Rough effort estimate (e.g., 0.1, 0.5, 1, 2, 4+).
                        * "complexity": (String) Subjective rating: "low", "medium", "high".
                        * "depends_on": (Array of Strings) List the file_path values of other tasks that must logically be completed before this one. Leave empty [] if none.
                        Constraint: Do NOT include any other text, explanations, summaries, apologies, notes, or conversational filler before the ## Suggested Project File Structure header, between the two sections, or after the final JSON code block. The output must only contain these two sections formatted exactly as specified, with the second section containing precisely one valid JSON object.

               
                """
    print("[cyan]Info: Formatting Task Decomposer prompt...[/cyan]")
    format_args = {
        "PRD_DOCUMENT": prd_markdown,
        "PRIMARY_LANGUAGE_HINT": primary_language_hint,
        "SYSTEM_CONTEXT": system_context_decomp,
        "OUTPUT_FORMAT_REQUIREMENT": output_format_req_decomp,
        "PROJECT_NAME": project_name,
                # Ensure ALL other placeholders required by task_decomposer.prompt are here
            }
    print(Panel(f"[cyan]DEBUG: Formatting args: {format_args}[/cyan]", title="DEBUG", border_style="cyan")) # Uncomment for debugging
    formatted_prompt_decomp = prompt_template_decomp.format(**format_args)

    print("[cyan]Info: Invoking LLM for Task Decomposition (Json format)...[/cyan]")
    response_decomp = llm.invoke(formatted_prompt_decomp)
    print(Panel(f"[cyan]DEBUG: Raw LLM output for decomposition: {response_decomp.content}[/cyan]", title="DEBUG", border_style="cyan")) # Uncomment for debugging


    if hasattr(response_decomp, 'content') and response_decomp.content:
            raw_llm_output_for_decomposition = response_decomp.content
            #print out json object
            print("[green]Success: Received Task Decomposition output from LLM.[/green]")
            return raw_llm_output_for_decomposition
    else:
            raise ValueError("LLM response object lacks content or content is empty.")# 

